### ISSUE TITLE
cannot update the default vlan

### ISSUE THREAD

**Issue by aym-frikha** [canonical/terraform-provider-maas#193]
Trying to use this provider to update the default vlan that has been created automatically by MAAS.
I imported it corrrectly but it imported it with vid = 0.
When I try to update the default vlan or use it in my script it says:  vid is required and "VID must be between 0 and 4094".
When I change the VID to 1 it works

**Comment by spdfnet** [comment]
Sounds like you might have mistyped  `maas_vlan.myVlan.vid` and used instead `maas_vlan.myVlan.id` ?

**Comment by skatsaounis** [comment]
Hi @aym-frikha 

Can you please paste here the JSON responce of `maas <profile_name> vlan read <default-fabric-name> <default-vlan-vid>` and also the exact import command you are trying to run plus the resource block definition of your module?

Thank you
