### ISSUE TITLE
Change from maas -> canonical ownership breaks OpenTofu

### ISSUE THREAD

**Issue by sempervictus** [canonical/terraform-provider-maas#221]
This should not be happening and does not happen when using the originally named `maas/maas` provider:
```hcl
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider canonical/maas: provider registry registry.opentofu.org does not have a provider named registry.opentofu.org/canonical/maas
│ 
│ All modules should specify their required_providers so that external consumers will get the correct providers when using a module. To see which modules are currently depending on canonical/maas, run the following command:
│     tofu providers
│ 
│ If you believe this provider is missing from the registry, please submit a issue on the OpenTofu Registry https://github.com/opentofu/registry/issues/
```
is this an omission or are Canonical's users supposed to utilize IBMs Terraform?

**Comment by troyanov** [comment]
We never added MAAS Terraform provider to the `registry.opentofu.org` and it ended up there because OpenTofu copied it from the Terraform registry. At the moment we are not maintaining existence of MAAS Terraform provider there.

**Comment by sempervictus** [comment]
Does that mean that Canonical does not support the Linux Foundation's Open Source effort and specifically forces users into the license-encumbered IBM/RedHat-owned Terraform workflow?

**Comment by troyanov** [comment]
> Does that mean that Canonical does not support the Linux Foundation's Open Source effort and specifically forces users into the license-encumbered IBM/RedHat-owned Terraform workflow?

@sempervictus I didn't say that. I said that **at the moment** we are not maintaining existence of MAAS Terraform provider there.

> Also pretty sure that the correct tag is not `completed` but `wontfix` - completion would entail maintenance in the Open Source repository referenced in the issue vs the proprietary one currently supported.

Thank you, this was a mistake and it is fixed now. 

@janosdebugs I apologize; I didn't mean to imply that OpenTofu copied Terraform's registry or violated their terms of service. I was not fully aware of how exactly OpenTofu fetched this information.

**Comment by troyanov** [comment]
@janosdebugs I am definitely looking forward to adding MAAS provider to the OpenTofu registry, however I by no means an official voice on this at the moment.

**Comment by troyanov** [comment]
`canonical/terraform-provider-maas` was added to the OpenTofu registry https://github.com/opentofu/registry/issues/747
